// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCENa6gNl0kkBdQyOUNtP3zBBTVa0-jJU',
    appId: '1:298219148516:web:3de7e9038a006159db48f1',
    messagingSenderId: '298219148516',
    projectId: 'sensor-lab-438fe',
    authDomain: 'sensor-lab-438fe.firebaseapp.com',
    storageBucket: 'sensor-lab-438fe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgQ66l4B01vW3ZhsTnNXy_aKSblymVNx8',
    appId: '1:298219148516:android:a5e8e70f28dfd81bdb48f1',
    messagingSenderId: '298219148516',
    projectId: 'sensor-lab-438fe',
    storageBucket: 'sensor-lab-438fe.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCENa6gNl0kkBdQyOUNtP3zBBTVa0-jJU',
    appId: '1:298219148516:web:3c62fb1bfba1908bdb48f1',
    messagingSenderId: '298219148516',
    projectId: 'sensor-lab-438fe',
    authDomain: 'sensor-lab-438fe.firebaseapp.com',
    storageBucket: 'sensor-lab-438fe.firebasestorage.app',
  );
}
